### ISSUE TITLE
Harmonize cytogenetics results in data projection

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#175]
### Description:

Consider "weakly positive/negative" positive/negative.
Jira ticket [PDXI-842](https://www.ebi.ac.uk/panda/jira/browse/PDXI-842?workflowName=jira&stepId=1)

Currently, when searching for "positive" the results that contain "weakly positive" are not returned.

### Acceptance criteria:

- [ ] cytogenetics results harmonized

**Comment by zperova** [comment]
We need to redo Cytogenetics templates to have a solution for this. This will require looking at how the data looks like - what are the values reported, and whether there is any type of standard values, etc.

**Comment by CsabaHalmagyi** [comment]
ETL taking this over, won't do.
