### ISSUE TITLE
Limit front end display for 50 rows

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#201]
### Description:

As a PDXFinder user, I don't want to see 50000 rows on the Details page in Molecular data table.

Jira [PDXI-821](https://www.ebi.ac.uk/panda/jira/browse/PDXI-821)

### Acceptance criteria:

- [ ] back end work to limit for 50 rows done
- [ ] front end work to limit for 50 rows done

**Comment by CsabaHalmagyi** [comment]
Done.
