### ISSUE TITLE
Extend UPDOG to load fusion data

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#215]
### Description:

As a PDXFinder developer, I want to extend the universal omic loader to enable upload of fusion data. 

Jira ticket [PDXI-801](https://www.ebi.ac.uk/panda/jira/browse/PDXI-801)

### Acceptance criteria:

- [ ] Fusion loading functionality in place and tested

**Comment by CsabaHalmagyi** [comment]
Closing, updog is retired.
