### ISSUE TITLE
PDX Services API

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#216]
### Description:

As a PDXFinder developer, I want PDXFinder to have API to enhance PDXFinder functionality as a resource.
Architectural changes discussed: https://docs.google.com/document/d/1jR6O31RcdeOj9h8FPqk2z7132WDcEsQo1wmp5DarSNU/edit#

An old Jira ticket [PDXI-772](https://www.ebi.ac.uk/panda/jira/browse/PDXI-772)

### Acceptance criteria:

- [ ] implementation discussed
- [ ] API in place

**Comment by CsabaHalmagyi** [comment]
Done, closing.
