### ISSUE TITLE
Include universal data exporter to AdminInterface

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#221]
### Description:

As a PDXFinder developer, I want to export data through the AdminInterface.
Jira ticket [PDXI-701](https://www.ebi.ac.uk/panda/jira/browse/PDXI-701)

### Acceptance criteria:

- [ ] export of data through AI is enabled

**Comment by Afollet** [comment]
This is no longer relevant

**Comment by CsabaHalmagyi** [comment]
Done, API endpoint added.
