### ISSUE TITLE
Update JS dependencies that have security vulnerabilities

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#225]
### Description:

As a PDXFinder developer, I want to ensure there are no security vulnerabilities. 

Jira ticket [PDXI-650](https://www.ebi.ac.uk/panda/jira/browse/PDXI-650)

### Acceptance criteria:

- [ ] the following is done:

Update npm packages that have been flagged as moderate severity or higher by github:

(critical) set-value
(critical) mixin-deep
(high) handlebars
(critical) lodash.mergewidth
(moderate) mem
(high) js-yaml
(high) ws
(moderate) fstream
(high) tar
(critical) lodash

**Comment by CsabaHalmagyi** [comment]
Done.
