### ISSUE TITLE
Record uptime and page downloaded in PDXFinder

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#230]
### Description:

As a developer, I want to have better metrics of PDXFinder usage.

Jira ticket [PDXI-449](https://www.ebi.ac.uk/panda/jira/browse/PDXI-449)

### Acceptance criteria:

- [ ] update Google Analytics to record uptime and page downloads in PDXFinder

**Comment by CsabaHalmagyi** [comment]
Done: UptimeRobot and Google Analytics have been implemented.
