### ISSUE TITLE
Create repo for useful Cypher queries

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#251]
### Description:

Repo for useful Cypher queries

Jira ticket [PDXI-723](https://www.ebi.ac.uk/panda/jira/browse/PDXI-723)

### Acceptance criteria:

- [ ] repo for useful Cypher queries

**Comment by zperova** [comment]
might not be relevant since will change database

**Comment by CsabaHalmagyi** [comment]
Won't do. Retiring Neo4j.
