### ISSUE TITLE
Load PMLB lung data

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#311]
### Description 

Load PMLB lung data

### Acceptance criteria:

- [x] data transformed
- [x] lung data in GitLab repo
- [x] data validation
- [x] data loaded to K8
- [x] run ETL for validation

**Comment by zperova** [comment]
waiting on the provider

**Comment by Afollet** [comment]
Lung and Pancreas are not ready for release in February

**Comment by Mandloi2309** [comment]
done @zperova
