### ISSUE TITLE
Make Updog more flexible with CNA/Expression data

### ISSUE THREAD

**Issue by Afollet** [PDCMFinder/pdxfinder#318]
Updog will not load data without HUGO gene nomenclature. This is a fair rule with Mutation data. However, it proves to be problematic with Expression, CNA, and other data types. A solution will need to be devised to support these types with either no gene symbol or multiple. If multiple exits, they should be able to fit into one cell of a tsv to reduce tsv bloating.

#########ACCEPTANCE CRITERIA##########
- [ ] Investigated solutions
- [ ] made changes to updog
- [ ] piloted solution
- [ ] change data were necessary
- [ ] merge to dev

**Comment by CsabaHalmagyi** [comment]
Won't do, UPDOG is retired.
