### ISSUE TITLE
Re-load rows with missing HGNC symbols - CRL Affymetrix HGU133plus2

### ISSUE THREAD

**Issue by Afollet** [PDCMFinder/pdxfinder#325]
See ticket: #213

Data points were filtered because they did not have HGNC symbols. These need to be restored once the data model is updated to support these. A reverse to commit 0bcb4e20c6f7c8e514d6b18810bdb67c0de0abdf

See README in data_quarantine/UPDOG/CRL/expression/microarray/ in Git repository

###### ACCEPTANCE CRITERIA #############

- [ ] data points are restored and commited
- [ ] data quarantine files are deleted

**Comment by zperova** [comment]
push the data that we have now

**Comment by zperova** [comment]
not all the points have been restored - 10-20% remain, exact number is documentation
