### ISSUE TITLE
Clean trailing spaces and lower case strings in Updog Harmonization

### ISSUE THREAD

**Issue by Afollet** [PDCMFinder/pdxfinder#354]
Trailing spaces and arbitrary capitalization carry no information on certain input values and can often prevent data from being inline causing extra cleaning work. 

###### ACCEPTANCE CRITERIA ########

- [ ] values that need cleaning are agreed upon
- [ ] Trimming is implemented
- [ ] lower casing is implemented

**Comment by CsabaHalmagyi** [comment]
Won't do, UPDOG is retired.
