### ISSUE TITLE
Extend validator for mol data templates

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#384]
### Description

As a developer, I want to have reliable validation for the data templates to avoid validation on loading.

Validation rules: https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Data+Validation

### Acceptance criteria

- [x] extend context and syntax validation in mol data templates
- [x] extend command line interface

**Comment by Afollet** [comment]
done

**Comment by zperova** [comment]
this is duplicate Epic of #602
