### ISSUE TITLE
Harmonize Platform values in Sample Platform template

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#428]
### Description 

As a PDX Finder user, I want to have a clear understanding of what platform has been used to get the data for PDX models from different providers.

List of all possible sample platforms and ideas on how to harmonize are here: https://docs.google.com/spreadsheets/d/1CL2Hl6e0ikEer6XM3kVY4gRjRv3gqOTQwUocPhEV6BM/edit#gid=0

### Acceptance criteria

- [x] decide on the list of harmonized values
- [x] update template
- [x] update template validator
- [x] fix submitted data

**Comment by Mandloi2309** [comment]
https://docs.google.com/document/d/1m2NUHtQwGeHFdlOxyDBF03oeCbDiJr50j0VOHO5dAGg/edit?usp=sharing

**Comment by Mandloi2309** [comment]
done
