### ISSUE TITLE
Load recent data from PDMR 

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#483]
### Description

As a developer, I want to load the latest PDMR data to the PDX Finder.

### Acceptance criteria
- [x] data validation
- [x] data loaded to K8

**Comment by Afollet** [comment]
@zperova there are hundreds of full genes expression data sets available for us on PDMR. I think we all forgot about this. It might be a good time to consider extending our current pipelines to retrieve and format this data the the PDX Finder.

**Comment by zperova** [comment]
Will not load for this release to focus on existing models' metadata improvements.

**Comment by Mandloi2309** [comment]
Data is validated and mutation data is lifted to genome assembly GRch38 and is ready to be loaded. I will load it when I have access to my EBI device.

**Comment by zperova** [comment]
Left to do:
- copy data from local repo to Kubernetes
- prepare the data - reload h2 database
- mapping in Admin UI @zperova 
- run ETL to load mapped data

**Comment by zperova** [comment]
New ticket for these:

- [ ] mapping of unmapped entities
- [ ] run ETL for validation

closing
