### ISSUE TITLE
Investigate the need for adding additional NCIT Ontology branches to ONToLIA

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#562]
### Description

As a developer, I want to have all needed terms available in the Admin UI to most precisely map diagnosis.

Point to consider:
- the more branches we pull, the longer it will be to load and index them.
As an alternative can consider requesting specific temrs from NCIT in the needed branch - currently pulling diagnosis from Malignant Neoplasm: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C9305

### Acceptance criteria

- [ ] plan discussed
- [ ] implemented

**Comment by zperova** [comment]
Of note, the current classification "Cancer by System" is not based on the same branch: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C27551&viewMode=All&siblings=false

**Comment by CsabaHalmagyi** [comment]
Added necessary branches to Ontolia already, closing. Reopen when new branches will be required.
