### ISSUE TITLE
Sync service with latest OLS for Admin UI back-end

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#593]
### Description

As a developer, I want to have a sync service to automatically update to the latest OLS version

Related Jira ticket PDXI-630

OLS is frequently updated, THEREFORE A BACK END SERVICE SHOULD BE CREATED to periodically synchronize the curated / validated mapped terms (used by the loader) from the Admin Interface's database with OLS to ensure the terms are updated based on any new change in OLS/NCIT

### Acceptance criteria

- [ ] ensure the database is using the latest version
- [ ] ensure the mapping rules have the latest version of the ontology labels (important for suggestion service)

**Comment by CsabaHalmagyi** [comment]
The new ETL approach solves this problem. Closing.

**Comment by zperova** [comment]
ETL will solve this by consuming Ontolia output. Closing.
