### ISSUE TITLE
2 treatment-resistant models from VHIO_BC118

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#610]
### Description

Add 2 treatment-resistant BC models from VHIO_BC118 model to PDX Finder.
2 treatment-resistant models to Trastuzumab (T-DM1) and associated data.
Communication from 23 March 2021.

### Acceptance criteria

- [x] metadata template sent
- [x] other templates sent: sample platform, expression, mutation, drug dosing
- [x] templates received
- [x] handed over for validation and loading

**Comment by zperova** [comment]
@zperova send a reminder

**Comment by zperova** [comment]
Reminder sent

**Comment by CsabaHalmagyi** [comment]
Removing from sprint, waiting for provider.
