### ISSUE TITLE
Handle especial case with molecular data for CRL

### ISSUE THREAD

**Issue by mauroz77** [PDCMFinder/pdxfinder#724]
The fields in molecular data that are relevant for CRL are not the same as for the rest of providers.

This is the list of fields by type:

cna and expression:
["sample_id","chromosome","strand","seq_start_position","seq_end_position","symbol","ucsc_gene_id","ncbi_gene_id","ensembl_gene_id", "platform"]

cyto:
["sample_id", "symbol","platform"]

Because those are the only fields we show for CRL, it doesn't make sense to load the rest of the fields in the database for that provider so we need to modify the system to ignore the unneeded fields.

**Comment by zperova** [comment]
this is not relevant now. closing
