### ISSUE TITLE
LIH cna cytobands conversion to seq position

### ISSUE THREAD

**Issue by Afollet** [PDCMFinder/pdxfinder#726]
As a developer I would like the data to be harmonized to the most common values types.

LIH has cytoband information instead of sequence start and stop positions in there CNA data. There is a conversion table, however there are many types of staining and it's unclear why they were used or accepted

###### ACCEPTANCE CRITERIA #######

- [x] cyto bands are resolved to sequence positions

**Comment by Mandloi2309** [comment]
done

**Comment by Mandloi2309** [comment]
all data points converted to genomic coordinates from their respective cytobands
