### ISSUE TITLE
TRACE data cleaning

### ISSUE THREAD

**Issue by Afollet** [PDCMFinder/pdxfinder#743]
The TRACE molecular_metadata has invalid patient_sample -> model relationship. That is, a patient refers to two different patient samples. This cannot be resolved without contacting TRACE.

**Comment by Afollet** [comment]
model_id sample_id_in_metatata sample_id_in_molecular_metadata
BRC0004PR BRC0004PRH0000000000VT9900 BRC0004PRH0000000000LS0100
BRC0013PR BRC0013PRH0000000000VT9900 BRC0013PRH0000000000LS0100
BRC0015PR BRC0015PRH0000000000VT9900 BRC0015PRH0000000000LS0100
BRC0020LY BRC0020LYH0000000000VT9900 BRC0020LYH0000000000LS0100
BRC0021PR BRC0021PRH0000000000VT0100 BRC0021PRH0000000000LS0100
EMC0047PR EMC0047PRH0000000000VT9900 EMC0047PRH0000000000LS0100
EMC0049PM EMC0049PMH0000000000VT9900 EMC0049PMH0000000000LS0100
EMC0063PM EMC0063PMH0000000000VT9900 EMC0063PMX0A02001TUMLS0100
EMC0080PR EMC0080PRH0000000000VT9900 EMC0080PRX0A01001TUMLS0100

**Comment by Afollet** [comment]
@CsabaHalmagyi

**Comment by zperova** [comment]
@zperova Contact Trace about these models

**Comment by zperova** [comment]
ongoing, waiting for provider comment

**Comment by zperova** [comment]
this data is currently at the state that it can be released. Can be updated later when get comment from provider.
