### ISSUE TITLE
Create data protection related content

### ISSUE THREAD

**Issue by CsabaHalmagyi** [PDCMFinder/pdxfinder#774]

**Comment by zperova** [comment]
Do together with @zperova

**Comment by zperova** [comment]
meeting scheduled

**Comment by CsabaHalmagyi** [comment]
Created the necessarry data protection entries, accessible here:
https://content.ebi.ac.uk/list-data-protection-records?title=pdcm&field_gdpr_workflow_state_value=All&field_gdpr_ebi_team_name_target_id_entityreference_filter=All

These are currently in draft mode, requires GTL approval before publishing.
