### ISSUE TITLE
cancermodels.org ingress controller

### ISSUE THREAD

**Issue by Afollet** [PDCMFinder/pdxfinder#775]
As a dev and user I want services to be available on the internet via dev.cancermodels.org and cancermodels.org

#### ACCEPTANCE CRITERIA ####
  * [x] Ingress controller has been mapped to internal resources on both hx and hh
  * [x] URL behave as desired
  * [x] external load balancer www6 forwards traffic to the ingress controllers on HX and HH to allow internet access

**Comment by CsabaHalmagyi** [comment]
Waiting for the wild card domain.

**Comment by Afollet** [comment]
@CsabaHalmagyi any follow ups to this?

We can put Dev up on CancerModels.org if it's easier. I'm not sure if we want a wild card domain if we are not going to expose dev.cancermodels.org

**Comment by Afollet** [comment]
Maybe we can limit traffic to EBI IP's only on the EBI external load balancer.

**Comment by CsabaHalmagyi** [comment]
No update from purchasing about this, will follow up.

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
done
