### ISSUE TITLE
Script for cleaning Data repo

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#820]
### Description

As a developer, I want to clean up the Data repo.

### Acceptance criteria

- [x] Storing the `.xlsx` files in separate DIR
- [x] Rename `pdx_models.tsv` to `pdx_model.tsv`
- [x] Remove `field` column from the `.tsv` files
- [x] Remove comments from the `.tsv.` files to refine the data

**Comment by Mandloi2309** [comment]
This is done.
