### ISSUE TITLE
Deploy cancermodels.org landing page

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#821]
### Description

As a developer, I want to deploy PDCM Finder landing page to inform users that the site is coming soon.

### Acceptance criteria

- [x] chasing prod about mapping concermodels.org to internal ingress controller
- [x] deploy landing page

**Comment by zperova** [comment]
Sorting SSL certificate with purchasing

**Comment by zperova** [comment]
wildcard SSL cwrtificate purchased

**Comment by zperova** [comment]
moving to the next sprint. no response from web-prod still

**Comment by ficolo** [comment]
Plan to move forward:

- [ ] We need the certificate to be sent from purchasing to web production.
- [ ] Apply Alex ingress config files on the web production cluster.  
    - [ ]  Check that both HX and HH k8s cluster have the right setup in place, meaning a namespace for both the Frontend and Backend deployments
    - [ ]  Create setup for CI/CD on the fallback cluster
- [ ] Reply the email to www-prod with the full URL, ingress controller name and namespace.
- [ ] Email with other members of the www-prod team that were able to help us with other mappings in the past (pdx-gun case).

**Comment by ficolo** [comment]
Secondary backend deployment on HX is missing DB access

**Comment by zperova** [comment]
Close this ticket and make a new one specifically for the landing page mapping
