### ISSUE TITLE
Design: Ontology treatment and Ontology regimen connection within the database

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#824]
### Description

As a developer, I want to have a correct relationship between ontology treatment and regimen in the database for search purposes.

### Acceptance criteria

- [x] designed

**Comment by mauroz77** [comment]
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/bab8776f-529f-42c8-8202-a9c95a42f308)

**Comment by zperova** [comment]
done, closing
