### ISSUE TITLE
Re-design of the Search page

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#844]
### Description

As a developer, I want to have the most user-friendly search page.

### Acceptance criteria

- [x] mock-ups created
- [x] mockups discussed
- [x] chosen design implemented

**Comment by ficolo** [comment]
https://www.figma.com/proto/CAURgZzkhMIhxYqbltMQSH/cancermodels.org---Web-Design?node-id=139%3A6

**Comment by zperova** [comment]
done
