### ISSUE TITLE
Re-design of the Details page

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#845]
### Description

As a developer, I want to have the most user-friendly Details page.

### Acceptance criteria

- [x] mock-ups created
- [x] mockups discussed
- [x] chosen design implemented

**Comment by ficolo** [comment]
https://www.figma.com/file/CAURgZzkhMIhxYqbltMQSH/cancermodels.org---Web-Design?node-id=0%3A1
