### ISSUE TITLE
Make an internal flowchart for data submission process

### ISSUE THREAD

**Issue by zperova** [PDCMFinder/pdxfinder#848]
### Description

As a developer, I want to have a clear idea of all the steps in the process of data submission.

### Acceptance criteria

- [x] flowchart draft
- [x] draft discussed
- [x] flowchart in documentation

**Comment by zperova** [comment]
this will be addressed after AACR 2022 and when everyone is back to work. Sprint starting 4 May

**Comment by Mandloi2309** [comment]
https://lucid.app/lucidchart/4cb8b01b-a6f7-4c8c-982a-b6b7ccfac1e6/edit?invitationId=inv_13e26e96-7c7b-4e08-897b-2e161563a9fc&page=0_0#

**Comment by mauroz77** [comment]
It looks good

**Comment by Mandloi2309** [comment]
https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Data+Integration+Proccess
