### ISSUE TITLE
Discussion: Database model refining

### ISSUE THREAD

**Issue by mauroz77** [PDCMFinder/pdxfinder#851]
As a developer, I want to have a database model as simple as possible. This can involve the deletion of tables/columns in the database if doing so still allows us to represent the things we want to represent.

When we have less tables/columns we get 3 benefits:
- A schema that is easier to understand
- Less code in the project
- Less execution time (a table less is a spark job less we need to execute)

Things that I think we could remove:

### Diagnosis table
At the beginning of the project it seemed to be a good idea to have a table to keep the diagnosis (patient's initial diagnosis and patient sample's diagnosis). As a general rule it's recommended to extract columns, especially if they are text, into separate tables if several records in other tables can reference a single value: for example, hundreds of patients could have the same initial diagnosis so we store it once and then other tables just need to reference that single record. In this way we avoid redundancy and some potential issues.

However in our specific case, those diagnosis' values are just intermediate values in our process: they by themselves don't represent a "controlled vocabulary", they are the input for the harmonisation process and the harmonised diagnosis are the ones we want to present to the user.

#### Proposal 
To delete the Diagnosis table and store the values as text in both patient and patient_sample tables. 

### Patient_snapshot
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/9c6ac2f0-fe76-40b2-ba6a-58971d452a7d)

We currently have 2 tables to represent one record in the patient_sample sheet in metadata: patient_sample and patient_snapshot. That was done that way to reflect as close as possible the neo4j schema. I'd like to reevaluate this, I don't think we need the  patient_snapshot table. We could keep all the information into the patient_sample.

#### Proposal 

- To delete the patient_snapshot table move all its attributes to the patient_sample table. 
- To check if all fields are needed. The columns of this new table would be:
   
    - id
    - diagnosis
    - external_patient_sample_id
    - grade
    - grading_system
    - stage
    - staging_system
    - primary_site_id
    - collection_site_id
    - prior_treatment
    - tumour_type_id
    - model_id
    - patient_id
    - age_in_years_at_collection
    - collection_event
    - collection_date
    - months_since_collection_1
    - treatment_naive_at_collection
    - virology_status

## Acceptance Criteria
- [x] Discussion with @zperova  about the proposed changes, either in comments in this ticket or a meeting if needed.

**Comment by mauroz77** [comment]
@zperova could you please have a look at this? We can have a meeting if needed. Thanks

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
will discuss Sprint 4 May

**Comment by zperova** [comment]
schedule another meeting

**Comment by mauroz77** [comment]
Meeting on 20-sep-2022, changes discussed and approved. @zperova
